### ISSUE TITLE
The given configuration is invalid. Reason: Expected one of #, input, filter, output at line 46, column 1 (byte 1218) after  {:level=>:fatal}

### ISSUE THREAD

**Issue by DARKSTAR6** [SMAPPER/Logstash-Configs#1]
Not sure which configuration file it is, but i'm getting the above error.

**Comment by DARKSTAR6** [comment]
I performed a cat /etc/logstash/conf.d/* > /tmp/total.conf and found a line that seems to be missing a break. 
The line: 
"wget https://github.com/SMAPPER/Logstash-Configs/raw/master/freq/xls.freq# Author: Justin Henderson"
Looks as if it missed a new line. Going to manually fix it and see if that corrects it.

**Comment by DARKSTAR6** [comment]
Turns out i'm retarded.

**Comment by ANDERSONTECHWERKS** [comment]
I wish I could recall @maltewhiite. Unfortunately: This was an issue from ~5 years ago, and I do not entirely recall what I did. Apologies.

**Comment by maltewhiite** [comment]
I figured out what is was. 
Turns out you can't have comments inside hashes.
